spring:
  output:
    ansi:
      enabled: always
  application:
    name: "Sample App" 
server:
  port: 8080
  servlet:
    context-path: /SampleApp
logging:
  level:
    root: INFO
    br.com.wsoubar: DEBUG